"""Production Open Policy Agent (OPA) Bundle Generator & Deployment Architecture Service."""
from __future__ import annotations

import json
from typing import Any, Dict, List
from pydantic import BaseModel

from app.abac.services.policy_repository import ExtendedPolicyModel, policy_repository


class OPABundleManifest(BaseModel):
    roots: List[str] = ["compliance/abac"]
    metadata: Dict[str, Any]


class OPABundleExport(BaseModel):
    manifest: OPABundleManifest
    policies: Dict[str, str]
    deployment_guides: Dict[str, str]


class OPAGeneratorService:
    """Generates production-compatible CNCF Open Policy Agent (OPA) Rego bundles and deployment manifests."""

    @staticmethod
    def generate_bundle(policies: Optional[List[ExtendedPolicyModel]] = None) -> OPABundleExport:
        active_policies = policies or policy_repository.get_published_policies()

        manifest = OPABundleManifest(
            roots=["compliance/abac"],
            metadata={
                "version": "1.0.0",
                "generated_by": "ComplianceAI Enterprise Authorization Platform",
                "policy_count": len(active_policies),
                "engine": "Open Policy Agent (OPA) v0.68+",
            },
        )

        # 1. Main Authorization Policy (authz.rego)
        authz_rego = OPAGeneratorService._build_authz_rego(active_policies)

        # 2. Risk Engine Policy (risk_rules.rego)
        risk_rego = OPAGeneratorService._build_risk_rego()

        # 3. Clearance Verification Policy (clearance_rules.rego)
        clearance_rego = OPAGeneratorService._build_clearance_rego()

        # 4. Obligations Engine Policy (obligations.rego)
        obligations_rego = OPAGeneratorService._build_obligations_rego()

        # Deployment Guides
        guides = {
            "kubernetes": OPAGeneratorService._k8s_deployment_guide(),
            "envoy": OPAGeneratorService._envoy_deployment_guide(),
            "istio": OPAGeneratorService._istio_deployment_guide(),
            "api_gateway": OPAGeneratorService._gateway_deployment_guide(),
        }

        return OPABundleExport(
            manifest=manifest,
            policies={
                "authz.rego": authz_rego,
                "risk_rules.rego": risk_rego,
                "clearance_rules.rego": clearance_rego,
                "obligations.rego": obligations_rego,
            },
            deployment_guides=guides,
        )

    @staticmethod
    def _build_authz_rego(policies: List[ExtendedPolicyModel]) -> str:
        rules_str_list = []
        for p in policies:
            action_match = p.actions[0] if p.actions else "*"
            dept_match = p.departments[0] if p.departments else "*"
            clearance_req = p.conditions.get("min_clearance", "internal") if p.conditions else "internal"
            effect_keyword = "allow" if p.effect.upper() == "PERMIT" else "deny"

            rule = f"""# Policy ID: {p.policy_id} ({p.name})
# Priority: {p.priority} | Status: {p.status} | Version: {p.version}
{effect_keyword} {{
    input.action == "{action_match}"
    input.resource.department == "{dept_match}"
    clearance_satisfied
    not high_risk_detected
}}"""
            rules_str_list.append(rule)

        joined_rules = "\n\n".join(rules_str_list)

        return f"""# CNCF Open Policy Agent (OPA) Authorization Policy
# Package: compliance.abac
# Auto-generated by ComplianceAI Zero-Trust Authorization Engine

package compliance.abac

import future.keywords.in
import future.keywords.every

default allow = false

# Global High-Risk Denial Directive (Risk Score >= 80)
deny {{
    input.subject.risk_score >= 80
}}

# Central Admin Default Bypass
allow {{
    input.subject.role == "central_admin"
}}

{joined_rules}
"""

    @staticmethod
    def _build_risk_rego() -> str:
        return """# Risk Engine Rego Module
package compliance.abac.risk

default high_risk = false

high_risk {
    input.subject.risk_score >= 80
}

calculated_risk = score {
    score := input.subject.risk_score
}
"""

    @staticmethod
    def _build_clearance_rego() -> str:
        return """# Clearance Verification Rego Module
package compliance.abac.clearance

clearance_rank := {
    "Public": 1,
    "Internal": 2,
    "Confidential": 3,
    "Restricted": 4,
    "Top Secret": 5
}

clearance_satisfied {
    user_rank := clearance_rank[input.subject.clearance_level]
    required_rank := clearance_rank[input.resource.classification]
    user_rank >= required_rank
}
"""

    @staticmethod
    def _build_obligations_rego() -> str:
        return """# Obligations Engine Rego Module
package compliance.abac.obligations

obligations[ob] {
    input.resource.contains_pii == true
    ob := "Mask PAN"
}

obligations[ob] {
    input.resource.contains_pii == true
    ob := "Mask Aadhaar"
}

obligations[ob] {
    input.subject.risk_score > 60
    ob := "Disable Download"
}
"""

    @staticmethod
    def _k8s_deployment_guide() -> str:
        return """# Kubernetes OPA Gatekeeper & Sidecar Deployment
1. Deploy bundle as a ConfigMap:
   `kubectl create configmap opa-abac-bundle --from-file=authz.rego`
2. Mount to OPA Sidecar container in Deployment:
   ```yaml
   containers:
   - name: opa
     image: openpolicyagent/opa:0.68.0-envoy
     args: ["run", "--server", "/policies"]
     volumeMounts:
     - name: opa-policy
       mountPath: /policies
   ```
"""

    @staticmethod
    def _envoy_deployment_guide() -> str:
        return """# Envoy External Authorization Filter Configuration
Add `envoy.filters.http.ext_authz` gRPC filter pointing to OPA Envoy sidecar:
```yaml
http_filters:
- name: envoy.filters.http.ext_authz
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
    grpc_service:
      envoy_grpc:
        cluster_name: opa_grpc_cluster
```
"""

    @staticmethod
    def _istio_deployment_guide() -> str:
        return """# Istio Service Mesh AuthorizationPolicy
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: abac-opa-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: complianceai-backend
  action: CUSTOM
  provider:
    name: opa-ext-authz-grpc
```
"""

    @staticmethod
    def _gateway_deployment_guide() -> str:
        return """# Enterprise API Gateway Integration (Kong / Azure APIM / AWS API Gateway)
1. Export bundle JSON endpoint `/api/v1/abac/opa-bundle`.
2. Configure Gateway OPA Plugin to fetch policy bundles on hot reload.
3. Pass JWT claims in `X-JWT-Claims` header for sub-millisecond local evaluation.
"""


opa_generator = OPAGeneratorService()
